spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3307/fast_sns?rewriteBatchedStatements=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    password: qwer1234
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true